global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'mspoc1'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['mspoc1:8080']
    tls_config:
      insecure_skip_verify: true
