apiVersion: v1
kind: ConfigMap
metadata:
 annotations:
  use-subpath: "true"
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'mspoc1'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['mspoc1:8080']
        tls_config:
          insecure_skip_verify: true

      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor:8080']
